[build]
  base = "frontend/"
  command = "npm run build"
  publish = "frontend/.next"

[context.production.environment]
  NEXT_PUBLIC_API_BASE_URL = "https://adminpanelproject-production-3ceb.up.railway.app/api"
