[build]
  # Garante que as dependências sejam instaladas antes de rodar o build
  command = "npm install && npm run build"
  base = "frontend/"
  publish = "frontend/.next"

[context.production.environment]
  NEXT_PUBLIC_API_BASE_URL = "https://adminpanelproject-production-3ceb.up.railway.app/api"
